name: Lint and Test project
on:
  pull_request:
    branches: [ "dev" ]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      # build the app with docker-compose
      - name: build
        run: |
          cd api/
          npm install
          npm run lint
      - name: run unit tests
        run: |
          cd api/
          npm test