version: '3'
services:

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
      target: build

    image: didz-api
    ports:
      - "3000:3000" # expose-to-the-world : only-in-the-docker
    networks:
      - didz_network
    container_name: didz-api
    

  ipfs:
    image: ipfs/kubo:master-latest
    volumes:
      - ./ipfs-export:/export
      - ./ipfs-data:/data/ipfs
    environment:
      IPFS_PROFILE: server
    ports:
      - "127.0.0.1:4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    networks:
      - didz_network
    container_name: didz-ipfs

networks:
  didz_network: